# yaml-language-server: =https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ElroiTheCreator.HolyBible
PackageVersion: 1.0.0
InstallerType: portable
Commands:
  - holybible
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Elroi-thecreator/bibleweb/releases/download/v1.0.0/HolyBible-Portable.exe
    InstallerSha256: B4A879E78930BE352DEA116E5009753C198B3133DE952CCEB2B32F6D542C3E16
ManifestType: installer
ManifestVersion: 1.6.0
